server:
  port: 8083
  servlet:
    context-path: /series/

spring:
  application:
    name: serie-service
  zipkin:
    base-url: http://zipkin-service:9411/
  config:
    import: optional:configserver:http://CONFIG-SERVER:8888
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672
queue:
  serie:
    name: SerieQueue
  data:
    mongodb:
      user: root
      password: example
      uri: mongodb://mongodb:27017/serie

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'